#!/bin/bash

echo "🚀 Privacy Demo Deployment Script"
echo "=================================="
echo ""

echo "📋 Prerequisites:"
echo "1. GitHub repository with your code"
echo "2. Render account (free tier available)"
echo "3. Vercel account (free tier available)"
echo "4. OpenAI API key"
echo "5. AWS credentials (if using S3 uploads)"
echo ""

echo "🔧 Step 1: Deploy Backend on Render"
echo "-----------------------------------"
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New +' and select 'Web Service'"
echo "3. Connect your GitHub repository"
echo "4. Configure:"
echo "   - Name: privacy-demo-backend"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "   - Plan: Free"
echo ""

echo "5. Set these environment variables in Render:"
echo "   NODE_ENV=production"
echo "   PORT=10000"
echo "   OPENAI_API_KEY=your_actual_openai_api_key"
echo "   AWS_ACCESS_KEY_ID=your_actual_aws_access_key"
echo "   AWS_SECRET_ACCESS_KEY=your_actual_aws_secret_key"
echo "   ENABLE_AUDIT_LLM=true"
echo "   FRONTEND_URL=https://your-vercel-frontend-url.vercel.app"
echo ""

echo "6. Click 'Create Web Service' and wait for deployment"
echo "7. Note your backend URL (e.g., https://privacy-demo-backend.onrender.com)"
echo ""

read -p "Press Enter when backend is deployed and you have the URL..."

echo ""
echo "🌐 Step 2: Deploy Frontend on Vercel"
echo "------------------------------------"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Click 'New Project'"
echo "3. Import your GitHub repository"
echo "4. Configure:"
echo "   - Framework Preset: Other"
echo "   - Root Directory: ./ (root of repository)"
echo "   - Build Command: Leave empty (static files)"
echo "   - Output Directory: frontend"
echo ""

echo "5. Set this environment variable in Vercel:"
echo "   REACT_APP_API_URL=https://your-render-backend-url.onrender.com"
echo "   (Replace with your actual Render backend URL)"
echo ""

echo "6. Click 'Deploy' and wait for deployment"
echo ""

read -p "Press Enter when frontend is deployed..."

echo ""
echo "✅ Step 3: Verify Deployment"
echo "----------------------------"
echo "1. Test backend: Visit your Render URL + /api/test_connection"
echo "2. Test frontend: Visit your Vercel URL"
echo "3. Check that frontend can connect to backend"
echo ""

echo "🔍 Troubleshooting:"
echo "- If you get CORS errors, make sure FRONTEND_URL is set correctly in Render"
echo "- If API calls fail, verify REACT_APP_API_URL is set correctly in Vercel"
echo "- Check Render and Vercel logs for any errors"
echo ""

echo "🎉 Deployment complete! Your app should now be running with:"
echo "- Backend: https://your-backend-url.onrender.com"
echo "- Frontend: https://your-frontend-url.vercel.app" 